services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  customers:
    build: .
    command: ["./customers"]
    environment:
      SERVICE_NAME: customers
      HTTP_ADDR: ":8081"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/customers_db?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8081"

  catalog:
    build: .
    command: ["./catalog"]
    environment:
      SERVICE_NAME: catalog
      HTTP_ADDR: ":8082"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/catalog_db?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8082"

  orders:
    build: .
    command: ["./orders"]
    environment:
      SERVICE_NAME: orders
      HTTP_ADDR: ":8083"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/orders_db?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8083:8083"
